### PR TITLE
Various fixes for issue #8

### LINKED ISSUE #8: Numerous issues on master branch.
`prometheus.go#prometheusScraper`
Logging is commented out, presumably to hide the double initialisation due to race condition or other bug?
Not sure if this does not occur when running in 'local' mode.

`apm.go#New`:
Initialised from both:
- `main.go#main`
  - `defer shutdown(..., startAPM(ctx, cfgs))`
- `apm.go#Global`
  - `if global == nil { ...; New(context.Background(), &Options{UseStdOut: false}); ... }`

---

When the logging is enabled, I see two messages (not always in the same order):
`[otel/http] starting prometheus scrape endpoint at: localhost:0/-/metrics`
`[otel/http] starting prometheus scrape endpoint at: localhost:9090/-/metrics`

see:
Image

Image

---

Also not sure why the Port was not defined for prometheus in apm.Options:

Image

---

And on a separate note: `syscall.SIGTSTP` does not exist on Windows:

Image

### PR DESCRIPTION
**Pull request by ph4n70m-nuk3r**
Partially fixes #8

### CODE REVIEW

File: internal/pkg/apm/prometheus.go [hunk 1]
```diff
@@ -28,20 +28,10 @@ func prometheusScraper(opts *Options) {
...
 	}
 
-	// logger.Info(
-	// 	"[otel/http] starting prometheus scrape endpoint",
-	// 	zap.String(
-	// 		"addr",
-	// 		fmt.Sprintf("localhost:%d/-/metrics", opts.PrometheusScrapePort),
-	// 	),
-	// )
+	fmt.Printf("[otel/http] starting prometheus metrics on :%d/-/metrics", opts.PrometheusScrapePort)
```
Comment (bnkamalesh) [inline internal/pkg/apm/prometheus.go]: why change logger to fmt.Printf? I think it'd be better to rely on the logger configurations to control the output. e.g. if the environment is local, then print text, if not print JSON etc.

File: internal/pkg/apm/prometheus.go [hunk 2]
```diff
@@ -28,20 +28,10 @@ func prometheusScraper(opts *Options) {
...
 	err := server.ListenAndServe()
 	if err != nil {
-		// logger.Error(
-		// 	"[otel/http] failed to serve metrics at:",
-		// 	zap.Error(err),
-		// 	zap.Uint16("port", opts.PrometheusScrapePort),
-		// )
-		return
+		fmt.Printf("[otel/http] failed to start prometheus metrics on :%d/-/metrics ; %+v", opts.PrometheusScrapePort, err)
+		panic(err)
```
Comment (bnkamalesh) [inline internal/pkg/apm/prometheus.go]: A utility package in my opinion should not `panic`, the caller should get to decide what to do in case of error. Previously I had just logged error and returned nothing because APM package is not considered a critical dependency of the app. 

I am assuming you're writing this in the same style as languages where try/catch is supported.

File: internal/pkg/sysignals/sysignals.go [hunk 3]
```diff
@@ -20,7 +20,8 @@ func NotifyErrorOnQuit(errs chan<- error, otherSignals ...syscall.Signal) {
 
 	for signalType := range interrupt {
 		switch signalType {
-		case syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT, syscall.SIGTSTP:
+		// syscall.SIGTSTP not supported on Windows.
```
Comment (bnkamalesh) [inline internal/pkg/sysignals/sysignals.go]: Why remove if not supported on Windows? So Windows will never send syscall.SIGTSTP, doesn't break this code. It is just one extra check. Wouldn't it be better to leave it here for other OS?

File: internal/pkg/apm/prometheus.go (hunk 1 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/prometheus.go]: Updated.

File: internal/pkg/apm/prometheus.go (hunk 2 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/prometheus.go]: Updated.

File: internal/pkg/sysignals/sysignals.go (hunk 3 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/sysignals/sysignals.go]: This does in fact break `go build` on Windows.

File: internal/pkg/apm/prometheus.go (hunk 2 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/prometheus.go]: Also no I was just under the assumption that APM is important enough to not ignore failures.

**Comment by ph4n70m-nuk3r** [comment]
Also I don't have Go support in the non-commercial IDE I'm using, which is making this a pain to work on:

image

**Comment by ph4n70m-nuk3r** [comment]
Here, that is working, if you want to change the use of `fmt.Printf(...)` to use your own logger implementation, please feel free to do so.
I think the main priority here should be correct initialisation and shutdown of metrics when the app is not running in 'local' mode, and handling the case where no collectorURL is configured for the tracer outside of 'local' mode.

File: internal/pkg/apm/apm.go [hunk 4]
```diff
@@ -140,9 +141,9 @@ func SetGlobal(apm *APM) {
 // Global gets global apm instance
 func Global() *APM {
 	if global == nil {
-		apm, _ := New(context.Background(), &Options{UseStdOut: false})
-		global = apm
-		return apm
+		message := "Attempt to use APM before it's been initialised."
+		fmt.Printf(message)
+		panic(message)
```
Comment (bnkamalesh) [inline internal/pkg/apm/apm.go]: why panic here?

File: internal/pkg/apm/apm.go [hunk 5]
```diff
@@ -187,6 +188,9 @@ func newTracer(ctx context.Context, opts *Options) (trace.TracerProvider, *Trace
 
 	if opts.UseStdOut {
 		exporter, err = stdouttrace.New()
+	} else if opts.CollectorURL == "" {
+		fmt.Printf("Using no-op tracer as CollectorURL is not set.")
```
Comment (bnkamalesh) [inline internal/pkg/apm/apm.go]: in this function it's checking different modes and using the one configured correctly. No need for logs.

File: internal/pkg/apm/apm.go (hunk 4 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/apm.go]: Because it should never be allowed to occur.
If it does occur, it means there is a bug, either improper usage or a race condition.

File: internal/pkg/apm/apm.go (hunk 5 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/apm.go]: Feel free to remove the informational message, my thoughts were that it would be prudent to warn the user that tracing is inactive due to configuration so they don't waste time troubleshooting on it.

File: internal/pkg/apm/prometheus.go (hunk 2 above)
Comment (bnkamalesh) [reply internal/pkg/apm/prometheus.go]: I think we should look at it like a utility package, e.g. Postgres driver, if the initialization fails for any reason, it wouldn't panic, rather return error, despite it being a critical dependency of the application.

File: internal/pkg/sysignals/sysignals.go (hunk 3 above)
Comment (bnkamalesh) [reply internal/pkg/sysignals/sysignals.go]: interesting, thank you for that. Just realized I haven't done anything on Windows for a very long time :smile:

Comment (ph4n70m-nuk3r) [reply internal/pkg/sysignals/sysignals.go]: Yes Windows is awful, but enterprise users have to tolerate it

File: internal/pkg/apm/apm.go (hunk 4 above)
Comment (bnkamalesh) [reply internal/pkg/apm/apm.go]: hmm, I implemented it trying to follow Go's philosophy of _**sane defaults**_. Now, I am split between the two, maybe it was not a good default. But I would definitely remove the fmt.Print, no need for log. Panic would suffice.

File: internal/pkg/apm/prometheus.go (hunk 2 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/prometheus.go]: That would be fine, but I wanted to keep these changes as small as possible and not change any signatures without knowing what you are open to accepting, feel free to go your own direction with this, the PR is mainly to highlight areas of improvement

File: internal/pkg/apm/prometheus.go [hunk 6]
```diff
@@ -24,24 +24,14 @@ func prometheusScraper(opts *Options) {
...
 	}
 
-	// logger.Info(
-	// 	"[otel/http] starting prometheus scrape endpoint",
-	// 	zap.String(
-	// 		"addr",
-	// 		fmt.Sprintf("localhost:%d/-/metrics", opts.PrometheusScrapePort),
-	// 	),
-	// )
+	fmt.Printf("[otel/http] starting prometheus metrics on :%d/-/metrics\n", opts.PrometheusScrapePort)
```
Comment (bnkamalesh) [inline internal/pkg/apm/prometheus.go]: can we revert to the logger instead of fmt.Printf, not sure why you decided to change.

File: main.go [hunk 7]
```diff
@@ -74,6 +74,13 @@ func main() {
 		}),
 	)
 
+	ap := startAPM(ctx, cfgs)
+	if ap == nil {
+		message := "Failed to start APM!"
+		fmt.Printf(message)
+		panic(message)
```
Comment (bnkamalesh) [inline main.go]: startAPM already has a panic, we don't have to check the same here again. Can revert to the previous implementation

File: internal/pkg/apm/prometheus.go [hunk 8]
```diff
@@ -24,24 +24,14 @@ func prometheusScraper(opts *Options) {
...
 	err := server.ListenAndServe()
 	if err != nil {
-		// logger.Error(
-		// 	"[otel/http] failed to serve metrics at:",
-		// 	zap.Error(err),
-		// 	zap.Uint16("port", opts.PrometheusScrapePort),
-		// )
-		return
+		fmt.Printf("[otel/http] failed to start prometheus metrics on :%d/-/metrics ; %+v\n", opts.PrometheusScrapePort, err)
```
Comment (bnkamalesh) [inline internal/pkg/apm/prometheus.go]: same here, not sure why this was changed from logger to fmt.Printf

File: internal/pkg/apm/prometheus.go (hunk 6 above)
Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/prometheus.go]: I was making some changes to that but I just ended up reverting them due to errors, I don't have a decent IDE for Go on my personal machine.

File: internal/pkg/apm/apm.go (hunk 5 above)
Comment (bnkamalesh) [reply internal/pkg/apm/apm.go]: yes it does make sense to help the devs, but there's info logs if they are working. Absence of it can be considered it's not working. Especially in case of starting the HTTP server to be scraped, we have the `[otel/http]` log.

**Comment by ph4n70m-nuk3r** [comment]
I think I've addressed most of your concerns.

**Comment by ph4n70m-nuk3r** [comment]
I think that's now everything as you requested.

File: internal/pkg/apm/apm.go [hunk 9]
```diff
@@ -187,6 +186,9 @@ func newTracer(ctx context.Context, opts *Options) (trace.TracerProvider, *Trace
 
 	if opts.UseStdOut {
 		exporter, err = stdouttrace.New()
+	} else if opts.CollectorURL == "" {
+		// Using no-op tracer as CollectorURL was not set.
+		return nil, nil, nil
```
Comment (bnkamalesh) [inline internal/pkg/apm/apm.go:191]: it does the same even if we do not return nil here, right?

Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/apm.go:191]: I'm not sure what you mean.
This branch it's to handle the case where the app isn't running in 'local' mode, and no collectorURL was set.
It explicitly skips configuring any tracer.
Without it, the code will fall through to:
```go
    tp, t := NewTracer(ctx, opts, exporter)
    return tp, t, nil
}
```

Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/apm.go:191]: Just for some context, I had errors starting this up when collectorURL was undefined (e.g. don't have an OTLP receiver for traces and don't want to use stdout traces).

Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/apm.go:191]: Worth mentioning that I'm not badge hunting or seeking any attribution on this, I'm 100% happy for you to commit these changes yourself as opposed to merging my fork.

I'm simply offering some minor changes to address some of the concerns and pain points which I experienced while running this.

Comment (bnkamalesh) [reply internal/pkg/apm/apm.go:191]: @ph4n70m-nuk3r I very much appreciate your contribution and a huge thank you for that! Just ironing out the deviations from _philosophies_ I've tried to follow till now.

Comment (ph4n70m-nuk3r) [reply internal/pkg/apm/apm.go:191]: No problem 👍
Please [let me know](https://youtu.be/-g6NH5kV5ic) when fixes are in main branch so I can delete my fork 🙂

**Review by bnkamalesh — DISMISSED** [review]
lgtm

**Comment by ph4n70m-nuk3r** [comment]
Screenshot_20250721-082614

**Comment by ph4n70m-nuk3r** [comment]
I added this (used fmt to test in case logging subsystem was inactive at that point):
Screenshot From 2025-07-21 09-29-25

But after sending SIGTERM I didn't see the output.
Screenshot From 2025-07-21 09-33-17
Screenshot From 2025-07-21 09-30-11

Seems a bit fishy, but for the time being I suppose it can just be:
```go
defer func() {
	_ := healthResp.Shutdown(ctx)
}()
```

**Review by bnkamalesh — APPROVED** [review]
lgtm

File: internal/pkg/apm/apm.go (hunk 9 above)
Comment (bnkamalesh) [reply internal/pkg/apm/apm.go:191]: @ph4n70m-nuk3r done.
